### ISSUE TITLE
Add option to start node without inmem balances index

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/go-cyber#296]
To reduce rank calculation time, previously we created in-memory account balances index. Maintain this index between cosmos updates become a nightmare. A lot of consensus bugs comes from that piece of code. General problem: cosmos has a lot of transactions, that touch account balances. You should handle all cases in order to keep consistency between in-memory and storage data.

Todo: Add option to launch node without an in-memory index.

**Comment by litvintech** [comment]
Hope I covered all balance change cases in Bostrom
