### ISSUE TITLE
Account stake for rank calculation

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/go-cyber#301]
Currently, we user `active_balance + sum(delegator_shares)`. Should be changed `active_balance + sum(delegator_shares * shares_ratio * validator_tokens)`.

If validator jailed `delegator_shares > delegator_shares * shares_ratio * validator_tokens `. Thus, you can attack the network by increasing your stake for rank calculation by delegating to jailed validators.

**Comment by litvintech** [comment]
@SaveTheAles Please make the test on this in our devnet

**Comment by litvintech** [comment]
Amperes is a resource token that used as a power stake, implemented in Bostrom
