### ISSUE TITLE
Add advanced guides

### ISSUE THREAD

**Issue by litvintech** [cybercongress/go-cyber#320]
We need advanced guides about:
@SaveTheAles 

- [ ] Genesis creation and launching for euler-5 @SaveTheAles 
- [ ] Economy for validators and delegators @SaveTheAles 
- [x] Rewards and slashing @SaveTheAles 
- [ ] Governance @SaveTheAles 
- [x] Multisig @SaveTheAles  @litvintech
- [ ] Rank calculation @litvintech 
- [x] Key management https://github.com/cybercongress/cyberd/issues/256 https://github.com/cybercongress/cyberd/issues/286 @SaveTheAles @litvintech
- [x] Launch process @xhipster @litvintech 
- [ ] Linking and bandwith @SaveTheAles
- [ ] Advanced linking for developers @SaveTheAles

Good example: 
[p2p validator about slashing](https://economy.p2p.org/slashing-overview-in-cosmos-network)
[p2p validator about cosmos economy](https://economy.p2p.org/introduction-to-cosmos-economy)

@xhipster please add more if I missed something

**Comment by xhipster** [comment]
We need the guide on creating and launching genesis. It seems the most important one indeed

**Comment by xhipster** [comment]
It looks like we define the launch process in the whitepaper
