### ISSUE TITLE
Delegation of energy and power

### ISSUE THREAD

**Issue by litvintech** [cybercongress/go-cyber#329]

**Comment by xhipster** [comment]
It looks like we really need this. I can not see the negative effects of implementing this

**Comment by xhipster** [comment]
I would love to have this feature as soon as possible, as only in this case I could use all my cyberlinking power seamlessly

**Comment by litvintech** [comment]
## Energy Module

#### Namings proposals
Energy/Route/CreateEnergyRoute/EditEnergyRoute/DeleteEnergyRoute
Energy/Delegation/DelegateEnergy/UndelegateEnergy/RedelegateEnergy

#### Open Questions
1. Names for energy routes? 
2. Max entries amount for src account (e.g max routes by src)? 
3. Need of block delay between changing given energy route (for given src-dst or alias)?
4. Charge tokens for creation of energy routes (for example to community pool)?

### Type 1
1. Agent operates with energy as absolute values. This means __value__ is amount of tokens which he woud like __to set__ on route.
2. Namings for routes
3. Direct creation and deletions of routes.
4. Potential support of multiple reroutes (e.g EditEnergyRoute)

#### Messages
1. CreateEnergyRoute (src, dst, alias)
    1. Creates route entry [src, dst, alias]
    2. Optionally execute payment to community pool
2. EditEnergyRoute (src, aliasFrom, aliasTo, value)
    1. Set value to alias [src, dst, value]
    2. ...
    5. Call hooks to update bandwidth and indexed balance for rank calculations
3. DeleteEnergyRoute (src, alias)
    1. Deletes route entry [src, dst, alias]
    2. Set __value__ (alias balance)  at __dst-->amount__ entry to 0
    3. Transfers __value__  (alias balance) from __module__ account to __src__ account
    4. Call hooks to update bandwidth and indexed balance for rank calculations


### Type 2  (currently implemented in draft)
1. Agent operates with  energy as difference value. This means __amount__ it is amount to __add or substract__ from.
2. No names for routes.
3. Creation and deletation of routes are hidden in conditions.

#### Messages
1. DelegatePower (src, dst, amount)
    1. Creates __dst__ account if not exist
    2. Transfers __amount__ from __src__ to __module__ account
    3. Creates or change delegations __entry__ in storage [src, dst, amount]
    4. Creates or change __amount__ to __dst-->amount__ entry
    5. Call hooks to update bandwidth and indexed balance for rank calculations
2. UndelegatePower(src, dst, amount)
    1. Transfers __amount__ from __module__ account to __src__ account
    2. Substract __amount__ from __dst-->amount__ entry
        1. Removes __dst-->amount__ entry if __amount__ to undelegare equals current  __dst__ __energy__
    3. Edit delegations __entry__ in storage [src, dst, amount]
        1. Removes delegations __entry__ if __amount__ to undelegare equals current __dst__ __energy__
    4. Call hooks to update bandwidth and indexed balance for rank calculations
3. RedelegatePower(src, dstFrom, dstTo, amount)
    1. Substract __amount__ from __dsFrom-->amount__ entry
    2. Edit delegations __entry__ in storage [src, dstFrom, amount]
        1. Removes delegations __entry__ if __amount__ to undelegare equals current __dstFrom__ __energy__
        2. Removes __dst-->amount__ entry if __amount__ to undelegare equals current __dstFrom__ __energy__
    3. Adds __amount__ to __dstTo-->amount__ entry
    4. Edit delegations __entry__ in storage [src, dstTo, amount]
    5. Call hooks to update bandwidth and indexed balance for rank calculations

### API
1. From Src Routes (all)
2. To Dst Routes (all)
3. Src-Dst Route
4. Dst Total Energy (from all dst)

#### Actions between Energy Module and others
Energy module calls function on bank's  proxy module which  holds hooks for bandwidth and indexed balance (for rank calc) updates.
