### ISSUE TITLE
Validator setup using Tendermint KMS + Ledger 

### ISSUE THREAD

**Issue by mrlp4** [cybercongress/go-cyber#393]
Add guide on how to create validator to participate in tenderming consensus with the keys stored on Ledger

**Comment by litvintech** [comment]
@mrlp4 please bring PR with docs for validators how to setup node using ledger

**Comment by mrlp4** [comment]
Docs are megred. 
https://github.com/cybercongress/go-cyber/blob/master/docs/validator_launch_with_tendermintKMS_and_ledger.md
