### ISSUE TITLE
Support easy install with brew tap

### ISSUE THREAD

**Issue by xhipster** [cybercongress/go-cyber#426]
## User Story

As a user of OSX I want to have ability to install the software using 2 lines

## Why Is this Needed?

Nearly all advanced Mac users use brew. It is helpful package manager.

## Definition of Done

```
brew tap cybercongress/cyberd
brew install cyberd
cyberdcli --version
~ 0.1.5
```

**Comment by xhipster** [comment]
Still хотеть

**Comment by mrlp4** [comment]
@xhipster will one line install [script](https://github.com/cybercongress/go-cyber/pull/507) fix this issue?

**Comment by mrlp4** [comment]
one-line installer created.
