### ISSUE TITLE
Modules renaming

### ISSUE THREAD

**Issue by litvintech** [cybercongress/go-cyber#440]
bandwidth -> energy
bank -> power
link -> graph, brain?
rank -> cyberrank
@xhipster What are you think about it?

**Comment by xhipster** [comment]
I agree with bandwidth -> energy, link -> graph and rank -> cyberrank, but not sure how bank connected to power

**Comment by litvintech** [comment]
Bostrom modules:
1. bandwidth
2. cyberbank
3. dmn (default mode network, ex cron)
4. graph
5. rank
6. grid (ex energy)
7. resources
