### ISSUE TITLE
Export cyberlinks from Euler-5

### ISSUE THREAD

**Issue by Aha203** [cybercongress/go-cyber#465]

**Comment by xhipster** [comment]
I think simple json file can be published to ipfs and and pinned so we can query it from https://cyber.page

**Comment by SaveTheAles** [comment]
An IPLS structure with addresses as keys should be better 

```json
{
   "address_0": [link0, link1...link_n],
   "address_1": [link0, link1...link_n]
   .
   .
}
```

so you can query your links array by address, and then relink it, just put an array to message field in the transaction

**Comment by xhipster** [comment]
@SaveTheAles Yep. Its good

**Comment by SaveTheAles** [comment]
The tool for that in LK repo
https://github.com/cybercongress/launch-kit/tree/0.1.0/cyberlink_exporter

**Comment by SaveTheAles** [comment]
the IPLD structure of euler-5 exported cyberlinks is
```
bafyreibnn7bfilbmkrxm2rwk5fe6qzzdvm2xen34cjdktdoex4uylb76z4
```

the snapshot of 1580000 block height
