### ISSUE TITLE
Update docs for euler-6

### ISSUE THREAD

**Issue by mrlp4** [cybercongress/go-cyber#503]
Run_validator doc
Ultimate_cli_guide
For usage without docker.

**Comment by litvintech** [comment]
Closed and merged in PRs:
Update run validator guide - https://github.com/cybercongress/go-cyber/pull/504
Documentation update for 0.1.6 - https://github.com/cybercongress/go-cyber/pull/507
Install cybercli script - https://github.com/cybercongress/go-cyber/pull/506
