### ISSUE TITLE
cyberdcli command returns empty array when it shoudlnt

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/go-cyber#522]
cyberdcli keys list returns an empty array [ ], when it should not. I can still manipulate keys using the query commands or any other commands like transfer, etc.

**Comment by mrlp4** [comment]
right after empty array was returned, it's necessary to check where at same moment point keyring-backend variable. run 'cyberdcli config --get keyring-backend'

**Comment by serejandmyself** [comment]
@mrlp4 os
