### ISSUE TITLE
Extra API endpoints to KG

### ISSUE THREAD

**Issue by litvintech** [cybercongress/go-cyber#543]
@xhipster @dimakorzhovnik @SaveTheAles Need your feedback from application development with endpoints (and needed data) what you need (for example backlinks, nested data, extra sorting, etc)

Need to formalize this set of new endpoints and I would like to add them in euler-7 release

**Comment by dimakorzhovnik** [comment]
rank by CID

**Comment by litvintech** [comment]
- backlinks by cid
- cyberlinks by account
- cyberlinks from given CID for given account
- backlinks to given CID for a given account(*)
- rank for given CID with optional proofs

**Comment by SaveTheAles** [comment]
Take a look at https://api.cyber.cybernode.ai/index_stats?

The stats chaotic change after refresh

Also, we need a real top 1000 at this endpoint https://api.cyber.cybernode.ai/top?page=0&perPage=1000

Expected 1000 CIDs with rank got 999 :)

**Comment by litvintech** [comment]
Done in Bostrom
