### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by resynth1943** [cybercongress/go-cyber#544]
After a few hours of reading, I can't say with confidence that I understand what this even *is*.

On the homepage, you state: 'Subscribe to someone to make your feed work. Until then, we'll show you the project feed. Start by adding a ledger to your pocket.'
This already raises various questions:

- how do I subscribe?
- what's my feed?
- why do I need a feed?
- what's the project feed?
- what's a ledger?
- why do I have a pocket?
- how do I search?
- what is the Game of Life?
- what is Euler?

Personally, I think the entire user-interface of cyber.space is unintuitive, as it raises more questions than it answers. It's also extremely confusing.

If we're going to #fuckgoogle, let's do it right.

First off, the homepage user interface could be a lot simpler. As the primary component of this program is search, that should be the main focus of attention on cyber.page.

When I search for 'hello', I see random addresses in list form. Am I doing something wrong?
Following this, what does my 'battery' do?

This will end up throwing people off, because users really don't know where to start. Could we please improve upon this?

**Comment by resynth1943** [comment]
(This may be more appropriate in the dot cyber repo, feel free to transfer.)

**Comment by serejandmyself** [comment]
Hey. Yes, it is appropriate to the dot cyber repo, spot on. 

Great feedback man. All of the answers (well, nearly all of them) can be found here: https://github.com/cybercongress/congress/blob/master/ecosystem/Cyber%20Homestead%20doc.md

or, cyber.page/brain/help

Never the less. You are right, the interface needs work. Thanks to user feedback we can make this work eventually =)

**Comment by resynth1943** [comment]
Haha, thanks for being so open to feedback 😛

I think we should mainly focus on making the user-interface simpler. Of course, documentation is good, but the fundamental concepts should be easily understood from the interface. Take Mastodon, for example (and Google, in their Search product -- others are just confusing).

We have to remember that this is being sold as an alternative. While I absolutely love the idea (IPFS *really* needs a search facility to take off IMHO, look at torrent sites like The Pirate Bay for an example.)

I could help to try and simplify it, although I would need time to understand how the frontend works.

**Comment by serejandmyself** [comment]
I'd be happy to facilitate some help between you and the dot.cyber team, where @xhipster is the main brain =) 

Of course, you are welcome to leave the comments (or PRs or whatever else) on your own too. In any case. We welcome contributions in a number of ways and (alas not very often as of lately) try to create some gitcoin tasks for these. There is also a community pool at the current testnet and it already functions. Of course, this is a long way of being perfect, but our goal is to build the project as self sustainable and to govern itself. 

Meh... Just realized that i went completely offtrack. I'm merely trying to say that there will be ways in the future to say thank you other that 'just thank you'.

In any case. I would be happy to connect directly too if you fancy it. Telegram / signal / etc

**Comment by resynth1943** [comment]
Hi @serejandmyself, I'd love to talk more about this. Could you please [contact me on Matrix](https://matrix.to/#/@resynth1943:privacytools.io)?
