### ISSUE TITLE
Bostrom discussion

### ISSUE THREAD

**Issue by litvintech** [cybercongress/go-cyber#546]
Discussion for roadmap:

#### Core
- Energy module
- Using KG in smart contracts 
    1. ranks
    2. cyberlinks
- cosmos-sdk v0.40 upgrade (enable native IBC)
    1. protobuf
    2. state
    3. huge refactoring
- APIs
    1. backlinks by cid
    2. cyberlinks by account
    3. cyberlinks from given CID for given account
    4. backlinks to given CID for given account
	5. rank for given CID
- Bandwidth based on gas meter*
- Refactoring
    1. Modules structure
    2. Links/CIDs storage
- Optimization
    1.  Application load
    2.  Search index
- Reputation
    1. disable karma or find new way
-  WASM
    1. Merkle-tree drop
-  Docs
    1. API docs
    2. rank/knowledge graph
    3. integration
    4. chain modules
    5. cyber wasm modules bindings
- Tooling
    1. cyberindex (djuno + optimized views)
    2. cosmos-js with cyber support
_________
#### Backlog during Euler-7
- CAPPS 
- Bonds module
- Enable IKP*
- [WASM] Rewards to contract deployers**
- [WASM] Knowledge Graph Prediction Markets (Prediction Market for rank value)**
- [WASM] Bandwidth Prediction Markets (For RS value)**
- [CUDA] Seq-Par Map Reduce for ranks calculations**
- [CUDA] Multi GPU for ranks calculations***
- Swarm support ***
- KG pruning (ouroboros)***
_________
#### IKP ideas
0. Propose cid for ranking...
1. cyberlinks transfer
2. cyberlinks get (all cyberlinks from given cid)
3. cyberlinks sub (new cyberlinks for given cid)
4. rank get (rank value for given cid)
5. rank sub (rank value for given cid)
6. backlinks get (all cyberlinks to given cid)
7. backlinks sub (all cyberlinks to given cid)
_________

**Comment by serejandmyself** [comment]
Only one comment: minimize `to-do` tasks, increase backlog. Nothing IMO, nothing wrong with launching everything listed here step by step, rather then having all of the possible features due for a certain date / event

Otherwise its looking more and more like the `never coming HF` =)

**Comment by litvintech** [comment]
New roadmap will be published soon
