### ISSUE TITLE
can't build arm binary for Jetson AGX 32Gb

### ISSUE THREAD

**Issue by Kwaskoff** [cybercongress/go-cyber#574]
### Current Behavior
I started this manual https://github.com/cybercongress/go-cyber/blob/dev/docs/run_validator.md
with skipping https://github.com/cybercongress/go-cyber/blob/dev/docs/run_validator.md#installing-nvidia-drivers
and https://github.com/cybercongress/go-cyber/blob/dev/docs/run_validator.md#install-cuda-toolkit
because this Nvidia device has native video device and Linux for Tegra (L4T) Ubuntu 18.04 with integrated drivers (NOT!! desktop videocard)
and on this step https://github.com/cybercongress/go-cyber/blob/dev/docs/run_validator.md#launching-cyberd-fullnode
```
Build cyber~Rank CUDA kernel:

cd ~/go-cyber/x/rank/cuda/
make
```
it looks cool
![image](https://user-images.githubusercontent.com/15308024/104373189-8d75d400-5531-11eb-8da0-8141fed8116a.png)
but 

```
cd ~/go-cyber
git checkout v0.1.6.4 (and with 1.6.2 the same problem)
make build
```

![image](https://user-images.githubusercontent.com/15308024/104374971-b4350a00-5533-11eb-9835-891db7a5fa38.png)
Problem of 
`/usr/bin/ld: cannot find -lgo_cosmwasm`

![image](https://user-images.githubusercontent.com/15308024/104375255-1f7edc00-5534-11eb-8e26-c6b73fc36131.png)
![image](https://user-images.githubusercontent.com/15308024/104375297-30c7e880-5534-11eb-97c7-76e93c80c191.png)

**Comment by litvintech** [comment]
Wasmer singlepass compiler doesn't have support on arm64
There is only one option to build cosmwasm locally using cranelift, but it's not recommended for production environment
