### ISSUE TITLE
API calls to list tokens on aggregator sites

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/go-cyber#580]
I want to list CYB and GOL on https://cosmos-cap.com/#/

I need API calls for the following:

- CYB: total supply, price in USD (can be derived from total cap in ATOM * by coingecko price for ATOM is USD - just an idea, feel free to use anything else)
- GOL: total supply, price in USD from uniswap 

Feel free to add other tokens, such as EUL, however I'm not certain thats required!

**Comment by serejandmyself** [comment]
@mrlp4 @SaveTheAles Preferably ASAP guys!

**Comment by mrlp4** [comment]
Api provided under 
https://market-data.cybernode.ai/api/coins/cyb
https://market-data.cybernode.ai/api/coins/gol
listed on cosmos-cap.
