### ISSUE TITLE
compile error calculate_gpu.go:94:18: not enough arguments in call to _Cfunc_calculate_rank

### ISSUE THREAD

**Issue by martrix78** [cybercongress/go-cyber#595]
### Current Behavior
[comment]: # (Describe what actually happened.)
Hi I am trying to make go-cyber and I get an error
### Expected Behavior
build and run 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
make build
### Log
[comment]: # (Also you can attach log to this issue.)
oem@oem-GF63-Thin-9RCX:~/go-cyber$ make build
go build -tags "netgo ledger cuda" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=cyber -X github.com/cosmos/cosmos-sdk/version.ServerName=cyberd -X github.com/cosmos/cosmos-sdk/version.ClientName=cyberdcli -X github.com/cosmos/cosmos-sdk/version.Version=0.1.6.2 -X github.com/cosmos/cosmos-sdk/version.Commit=e8ab6b2ecea8bce0e25dc5c14340498f3ca402e4 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,cuda"' -o build/cyberd ./cmd/cyberd
# github.com/cybercongress/go-cyber/x/rank/internal/keeper
x/rank/internal/keeper/calculate_gpu.go:94:18: not enough arguments in call to _Cfunc_calculate_rank
	have (*_Ctype_ulong, _Ctype_ulong, _Ctype_ulong, _Ctype_ulong, *_Ctype_uint, *_Ctype_uint, *_Ctype_ulong, *_Ctype_ulong, *_Ctype_ulong, *_Ctype_double, _Ctype_double, _Ctype_double)
	want (*_Ctype_ulong, _Ctype_ulong, _Ctype_ulong, _Ctype_ulong, *_Ctype_uint, *_Ctype_uint, *_Ctype_ulong, *_Ctype_ulong, *_Ctype_ulong, *_Ctype_double, _Ctype_double, _Ctype_double, *_Ctype_double, *_Ctype_double, *_Ctype_double)
make: *** [Makefile:82: build] Error 2

Go version 1.16.2
pls help me :(

**Comment by litvintech** [comment]
Please, ping me if issue are still here
