### ISSUE TITLE
Upgrade 1: Frey

### ISSUE THREAD

**Issue by litvintech** [cybercongress/go-cyber#617]
## Upgrades:
1. cosmos-sdk upgrade to v0.45.x
2. tendermint upgrade to v0.35.x
3. liquidity module upgrade v1.4.5+
4. IBC upgrade to v3.x
5. wasmd upgrade to v0.23+

## Features:
1. cyberlinks staking!
2. liquidity bindings to cosmwasm

## Fixes:
1. cyberlink and investmint messages amino encoding 

## Enhancements
1. bandwidth price adjustments to high cyberlinks demand

**Comment by faddat** [comment]
I'd like to assist you with this and I'd also like to suggest that you try this cosmos-sdk:

https://github.com/notional-labs/cosmos-sdk/tree/v0.45.1-allfast

and this iavl:

https://github.com/osmosis-labs/iavl/releases/tag/v0.17.3-osmo-v1

I am actually applying these patches to bostrom now as part of our (embarassinglgy lengthy) quest to put our bostrom node back up.

And in the end, all shall see SpacePussy and know that she's beautiful.

**Comment by mastercyb** [comment]
@litvintech Do I understand correctly that we remove staking of cyberlinks from this scope?

**Comment by mastercyb** [comment]
Also I would love to have names for upgrades. Lets start discussion
